spring:
    servr:
     port: 8080
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aluserinfo?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.plan.entity




